# Generated by Django 3.1.7 on 2021-03-08 06:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeatherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('city_name', models.CharField(blank=True, max_length=200, null=True)),
                ('weather_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('wind_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('temperature_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('visibility', models.IntegerField()),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('long', models.CharField(blank=True, max_length=20, null=True)),
                ('openweather_city_id', models.IntegerField()),
            ],
        ),
    ]
